[package]
name = "token_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.14.1", directory="yarn-project/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.14.1", directory="yarn-project/aztec-nr/value-note"}
safe_math = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.14.1", directory="yarn-project/aztec-nr/safe-math"}
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.14.1", directory="yarn-project/aztec-nr/authwit"}